<meta name="keywords" content="">
<meta name="description" content="">
<meta name="author" content="合肥付利购电子商务有限公司">
<meta name="copyright" content="合肥付利购电子商务有限公司版权所有">
<meta http-equiv="X-UA-Compatible" content="IE=edge,Chrome=1" />
<meta http-equiv="X-UA-Compatible" content="IE=9" />
<script src="/website/js/jquery-1.4.2.min.js"></script>
<script src="/website/js/jquery-1.8.3.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="/website/js/ie8.js"></script>

<!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<!--[if lt IE 9]>
 <link rel="stylesheet" type="text/css" href="/website/style/ie.min.css" media="screen" />
 <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
<![endif]-->
<!--[if IE]>
<script type="text/javascript" src="/website/js/jquery.placeholder.min.js"></script>
<script type="text/javascript">
        $(function () {
            // Invoke the plugin
              var width = $(window).width();
                        if(width > 1200){
                            $('.container').css({'width':'1170px'});
                        }else if(width < 768 && width < 992){
                            $('.container').css({'width':'750px'});
                        }else if(width > 992 && width < 1200){
                            $('.container').css({'width':'970px'});
                        }
            $('input, textarea').placeholder();
            $('.nav>.line').remove();
            var width = $(window).width();
            if(width < 1500){
                $('.header .container-fluid .f44').css({'font-size':'28px'});
                $('.header .container-fluid .f20').css({'font-size':'16px'});
            }
        });
    </script>
<![endif]-->

<link rel="stylesheet" href="/website/style/wap.min.css"/>
<script src="/website/js/superSlide.min.js"></script>
<script src="/website/js/handlebars.min.js"></script>
<script src="/website/js/jquery.lSelect.js"></script>
  <SCRIPT language=javascript type=text/javascript>
<!--
document.oncontextmenu=new Function('event.returnValue=false;');
document.onselectstart=new Function('event.returnValue=false;');
-->
  </SCRIPT>


