<meta name="keywords" content="">
<meta name="description" content="">
<meta name="author" content="合肥付利购电子商务有限公司">
<meta name="copyright" content="合肥付利购电子商务有限公司版权所有">
<meta http-equiv="X-UA-Compatible" content="IE=edge,Chrome=1" />
<meta http-equiv="X-UA-Compatible" content="IE=9" />
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<!-- 新 Bootstrap 核心 CSS 文件 -->
<link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!--[if lt IE 9]>
 <script src="//cdn.bootcss.com/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
 <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.js"></script>
<![endif]-->
<link rel="stylesheet" href="/bigData/style/common.min.css"/>
<script src="/website/js/superSlide.min.js"></script>




